version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "skip-changelog"
    target-branch: "develop"
    schedule:
      interval: "daily"
