version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    default_labels:
      - "dependencies"
      - "skip-changelog"
    target_branch: "develop"
    schedule:
      interval: "daily"