name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🔥 Breaking'
    labels:
      - 'breaking'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'infra'
  - title: '🧪 Experimental'
    labels:
      - 'experimental'
exclude-labels:
  - 'skip-changelog'
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
      - '/infra\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
      - '/hotfix\/.+/'
    title:
      - '/fix/i'
      - '/bug/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
change-template: '- (#$NUMBER) $TITLE - (thanks to @$AUTHOR)'
change-title-escapes: '\<*_&#@'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES