name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 1.11
      uses: actions/setup-java@v2.3.0
      with:
        distribution: 'adopt'
        java-version: '11'
        check-latest: true
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.0.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
