# Automates creation of Release Drafts using Release Drafter
# More Info: https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  update_release_draft:
    if: github.repository_owner == 'insideapp-oss'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
